{% set name = "trio-util" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a4b1db87191e56dfce3e6bc244d3232fa9f28ed4ec829c8ba22304f81400fe89

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - async_generator
    - trio >=0.11.0

test:
  imports:
    - trio_util
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/groove-x/trio-util
  license: MIT
  license_family: MIT
  # License file manually packaged: See https://github.com/groove-x/trio-util/pull/11
  license_file: LICENSE
  summary: Utility library for the Python Trio async/await framework
  doc_url: https://trio-util.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - dhirschfeld
